### ISSUE TITLE
It's possible a variant to use with LibreWolf

### ISSUE THREAD

**Issue by ajmasia** [nilp0inter/autofirma-nix#32]
Hi guys! Great job with this flake.

Currently I'm using LibreWolf. It;s possible use this flake with this browser?

Home Manager provide this settings: https://home-manager-options.extranix.com/?query=librewolf&release=release-24.05

Thanks!

**Comment by nilp0inter** [comment]
Sorry for the late reply.

It should be possible in principle to use `autofirma-nix` with `LibreWolf`. AFAIK, LibreWolf is a `Firefox` fork.  The only problem that I am seeing is that the options exposed by `home-manager` to configure `LibreWolf` are rather limited in comparison with the ones available for `Firefox`.

Two things you may try:

1. Change the Firefox package in home-manager to LibreWolf:

    ```nix
    programs.firefox.enable = true;
    programs.firefox.package = pkgs.librewolf
    ```
  
      And then apply the usual autofirma-nix configuration.

2. Apply manually the needed settings for the integration to work. Namely https://github.com/nilp0inter/autofirma-nix/blob/ec55ea98f88ac929d5257563587812a354dde947/nix/autofirma/hm-module.nix#L48-L53
   But maybe some changes are required in order to save these setting into the default LibreWorlf profile.  I am not sure.


Please note that I didn't try any of these and maybe the integration is not possible at all.

**Comment by ajmasia** [comment]
Thanks! I will try it!

**Comment by nilp0inter** [comment]
I will close this issue now, please feel free to reopen it if you have any further questions or comments.
